# Generated by Django 3.0.6 on 2020-05-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemAvailable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItems_has_ItemSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventoryItemType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemOS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSoftware', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purposes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purposeDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VMLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationStartDate', models.DateField(auto_now=True)),
                ('reservationEndDate', models.DateField()),
                ('reservationPurpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Purposes')),
                ('reservedFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservedForUser', to=settings.AUTH_USER_MODEL)),
                ('reservedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.InventoryItems')),
                ('reservingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanStartDate', models.DateField()),
                ('loanEndDate', models.DateField()),
                ('loanPurpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Purposes')),
                ('loanedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.InventoryItems')),
                ('loaningUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='itemDescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ItemDescription'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='itemOS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ItemOS'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='itemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.InventoryItemType'),
        ),
    ]
