# Generated by Django 3.0.6 on 2020-05-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItems_has_ItemSoftware',
        ),
    ]
