# Generated by Django 3.0.6 on 2020-05-28 12:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_inventoryitems_has_itemsoftware'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItems',
            new_name='InventoryItem',
        ),
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
        migrations.RenameModel(
            old_name='Purposes',
            new_name='Purpose',
        ),
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='VMLoans',
            new_name='VM',
        ),
        migrations.RenameModel(
            old_name='VMs',
            new_name='VMLoan',
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
