# Generated by Django 3.0.6 on 2020-05-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usertypes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserTypes',
        ),
    ]
