# Generated by Django 3.0.6 on 2020-05-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inventoryitemtype_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemtype',
            name='pp',
        ),
    ]
