# Generated by Django 3.0.6 on 2020-05-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_inventoryitemtype_pp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemtype',
            name='inventoryItemType',
        ),
    ]
