# Generated by Django 3.0.6 on 2020-05-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_inventoryitemtype_inventoryitemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemtype',
            name='inventoryItemType',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
