# Generated by Django 3.0.6 on 2020-05-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200529_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='itemDescription',
        ),
    ]
