# Generated by Django 3.0.6 on 2020-05-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_inventoryitem_itemdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemDescription',
        ),
    ]
