# Generated by Django 3.0.6 on 2020-05-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_inventoryitem_itemdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemSoftware',
        ),
    ]
