# Generated by Django 3.0.6 on 2020-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_itemsoftware'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSoftware', models.CharField(max_length=200)),
            ],
        ),
    ]
