# Generated by Django 3.0.6 on 2020-05-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_itemsoftware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loanPurpose',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservationPurpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
