# Generated by Django 3.0.6 on 2020-05-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200529_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purposeDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loanPurpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Purpose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationPurpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Purpose'),
            preserve_default=False,
        ),
    ]
