# Generated by Django 3.0.6 on 2020-05-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200529_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='itemSoftware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ItemSoftware'),
            preserve_default=False,
        ),
    ]
