# Generated by Django 3.0.6 on 2020-05-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_inventoryitem_itemsoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsoftware',
            name='itemSoftwareName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
