# Generated by Django 3.0.6 on 2020-06-02 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_itemsoftware_itemsoftwarename'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='VmName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmloan',
            name='loanEndDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vmloan',
            name='loanPurpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Purpose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmloan',
            name='loanStartDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vmloan',
            name='loanedVm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.VM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmloan',
            name='loaningUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='itemSoftware',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='itemSoftware',
            field=models.ManyToManyField(to='main.ItemSoftware'),
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='itemDescription',
            field=models.TextField(max_length=200),
        ),
    ]
