# Generated by Django 3.0.6 on 2020-06-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200602_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='vmDescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ItemDescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='vmEsxiHost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.InventoryItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='vmOS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ItemOS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='vmType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.InventoryItemType'),
            preserve_default=False,
        ),
    ]
