# Generated by Django 3.0.6 on 2020-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200602_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='purposeDescription',
            field=models.TextField(max_length=200),
        ),
    ]
