# Generated by Django 3.0.6 on 2020-06-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200529_0910'),
        ('main', '0022_auto_20200602_1100'),
    ]

    operations = [
    ]
